/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;


import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.filechooser.FileSystemView;






/**
 *
 * @author holij
 */
public class HOME extends javax.swing.JFrame {
        private String nombreUsuario;

    


    /**
     * Creates new form BIBLIOTECA
     */
     public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
        lblNOMBRE.setText(nombreUsuario);
    }
    public HOME() {
        
        initComponents();
        this.setTitle("Principal");
        this.setLocationRelativeTo(null);

        

  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNOMBRE = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnreportedocente = new javax.swing.JButton();
        btnreporteAdministrativo = new javax.swing.JButton();
        btnreporteVisitante = new javax.swing.JButton();
        btnreporteEstudiante = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 14)); // NOI18N
        jLabel2.setText("Inicio de sesion como:");

        lblNOMBRE.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        jToggleButton1.setText("Regresar Al Menu");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        btnreportedocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf (1).png"))); // NOI18N
        btnreportedocente.setText("Generar Reporte");
        btnreportedocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportedocenteActionPerformed(evt);
            }
        });

        btnreporteAdministrativo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf (1).png"))); // NOI18N
        btnreporteAdministrativo.setText("Generar Reporte");
        btnreporteAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteAdministrativoActionPerformed(evt);
            }
        });

        btnreporteVisitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf (1).png"))); // NOI18N
        btnreporteVisitante.setText("Generar Reporte");
        btnreporteVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteVisitanteActionPerformed(evt);
            }
        });

        btnreporteEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf (1).png"))); // NOI18N
        btnreporteEstudiante.setText("Generar Reporte");
        btnreporteEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteEstudianteActionPerformed(evt);
            }
        });

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnreportedocente)
                .addGap(45, 45, 45)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnreporteAdministrativo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(lblNOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnreporteEstudiante)
                                .addGap(40, 40, 40)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnreporteVisitante)
                                .addGap(0, 33, Short.MAX_VALUE))
                            .addComponent(jSeparator5))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnreportedocente)
                            .addComponent(btnreporteAdministrativo)))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnreporteVisitante))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(btnreporteEstudiante)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)
                        .addGap(209, 209, 209))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnreporteVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteVisitanteActionPerformed
        Document documento = new Document();

        conectar cc=new conectar();
        java.sql.Connection cn=cc.conexion();int Contador =1;
        try{
            FileSystemView view = FileSystemView.getFileSystemView();
            String ruta = view.getHomeDirectory().getPath() + "/Reporte_Visitante.pdf" ;
            PdfWriter.getInstance(documento, new FileOutputStream(ruta));
            documento.open();

            PdfPTable tablaDocente = new PdfPTable(7);
            tablaDocente.addCell("Nombre");
            tablaDocente.addCell("Correo");
            tablaDocente.addCell("Edad");
            tablaDocente.addCell("Genero");
            tablaDocente.addCell("Ciudad");
            tablaDocente.addCell("Identificacion");
            tablaDocente.addCell("Telefono");

            try{

                PreparedStatement pst=cn.prepareStatement("SELECT * FROM visitante");
                ResultSet rs =pst.executeQuery();
                if (rs.next()){
                    do{
                        tablaDocente.addCell(rs.getString(1));
                        tablaDocente.addCell(rs.getString(2));
                        tablaDocente.addCell(rs.getString(3));
                        tablaDocente.addCell(rs.getString(4));
                        tablaDocente.addCell(rs.getString(5));
                        tablaDocente.addCell(rs.getString(6));
                        tablaDocente.addCell(rs.getString(7));

                    }while(rs.next());
                    documento.add(tablaDocente);

                }
            }catch(DocumentException | SQLException e){

            }
            documento.close();
            JOptionPane.showMessageDialog(null, "El reporte fue creado con exito");
        }catch(DocumentException | HeadlessException | FileNotFoundException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnreporteVisitanteActionPerformed

    private void btnreporteAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteAdministrativoActionPerformed
        Document documento = new Document();

        conectar cc=new conectar();
        java.sql.Connection cn=cc.conexion();int Contador =1;
        try{
            FileSystemView view = FileSystemView.getFileSystemView();
            String ruta = view.getHomeDirectory().getPath() + "/Reporte_Administrativo.pdf" ;
            PdfWriter.getInstance(documento, new FileOutputStream(ruta));
            documento.open();

            PdfPTable tablaDocente = new PdfPTable(4);
            tablaDocente.addCell("Nombre");
            tablaDocente.addCell("Edad");
            tablaDocente.addCell("Genero");
            tablaDocente.addCell("Cargo");

            try{

                PreparedStatement pst=cn.prepareStatement("SELECT * FROM administrativo");
                ResultSet rs =pst.executeQuery();
                if (rs.next()){
                    do{
                        tablaDocente.addCell(rs.getString(1));
                        tablaDocente.addCell(rs.getString(2));
                        tablaDocente.addCell(rs.getString(3));
                        tablaDocente.addCell(rs.getString(4));

                    }while(rs.next());
                    documento.add(tablaDocente);

                }
            }catch(DocumentException | SQLException e){

            }
            documento.close();
            JOptionPane.showMessageDialog(null, "El reporte fue creado con exito");
        }catch(DocumentException | HeadlessException | FileNotFoundException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnreporteAdministrativoActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        PaginaPrincipal entrada = new PaginaPrincipal();
        entrada.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnreporteEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteEstudianteActionPerformed
        Document documento = new Document();

        conectar cc=new conectar();
        java.sql.Connection cn=cc.conexion();
        try{
            FileSystemView view = FileSystemView.getFileSystemView();
            String ruta = view.getHomeDirectory().getPath() + "/Reporte_Estudiante.pdf" ;
            PdfWriter.getInstance(documento, new FileOutputStream(ruta));
            documento.open();

            PdfPTable tablaDocente = new PdfPTable(12);
            tablaDocente.addCell("Nombre");
            tablaDocente.addCell("Genero");
            tablaDocente.addCell("Edad");
            tablaDocente.addCell("Direccion");
            tablaDocente.addCell("Telefono");
            tablaDocente.addCell("Ciudad");
            tablaDocente.addCell("Codigo");
            tablaDocente.addCell("Grado");
            tablaDocente.addCell("Identificacion");
            tablaDocente.addCell("Correo");
            tablaDocente.addCell("Jornada");
            tablaDocente.addCell("Afiliacion");

            try{

                PreparedStatement pst=cn.prepareStatement("SELECT * FROM estudiante");
                ResultSet rs =pst.executeQuery();
                if (rs.next()){
                    do{
                        tablaDocente.addCell(rs.getString(1));
                        tablaDocente.addCell(rs.getString(2));
                        tablaDocente.addCell(rs.getString(3));
                        tablaDocente.addCell(rs.getString(4));
                        tablaDocente.addCell(rs.getString(5));
                        tablaDocente.addCell(rs.getString(6));
                        tablaDocente.addCell(rs.getString(7));
                        tablaDocente.addCell(rs.getString(8));
                        tablaDocente.addCell(rs.getString(9));
                        tablaDocente.addCell(rs.getString(10));
                        tablaDocente.addCell(rs.getString(11));
                        tablaDocente.addCell(rs.getString(12));

                    }while(rs.next());
                    documento.add(tablaDocente);

                }
            }catch(DocumentException | SQLException e){

            }
            documento.close();
            JOptionPane.showMessageDialog(null, "El reporte fue creado con exito");
        }catch(DocumentException | HeadlessException | FileNotFoundException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnreporteEstudianteActionPerformed

    private void btnreportedocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportedocenteActionPerformed
        Document documento = new Document();

        conectar cc=new conectar();
        java.sql.Connection cn=cc.conexion();int Contador =1;
        try{
            FileSystemView view = FileSystemView.getFileSystemView();
            String ruta = view.getHomeDirectory().getPath() + "/Reporte_Docentes.pdf" ;
            PdfWriter.getInstance(documento, new FileOutputStream(ruta));
            documento.open();

            PdfPTable tablaDocente = new PdfPTable(7);
            tablaDocente.addCell("Nombre");
            tablaDocente.addCell("Correo");
            tablaDocente.addCell("Materia");
            tablaDocente.addCell("Edad");
            tablaDocente.addCell("Genero");
            tablaDocente.addCell("Jornada");
            tablaDocente.addCell("Identificacion");

            try{

                PreparedStatement pst=cn.prepareStatement("SELECT * FROM docente");
                ResultSet rs =pst.executeQuery();
                if (rs.next()){
                    do{
                        tablaDocente.addCell(rs.getString(1));
                        tablaDocente.addCell(rs.getString(2));
                        tablaDocente.addCell(rs.getString(3));
                        tablaDocente.addCell(rs.getString(4));
                        tablaDocente.addCell(rs.getString(5));
                        tablaDocente.addCell(rs.getString(6));
                        tablaDocente.addCell(rs.getString(7));

                    }while(rs.next());
                    documento.add(tablaDocente);

                }
            }catch(DocumentException | SQLException e){

            }
            documento.close();
            JOptionPane.showMessageDialog(null, "El reporte fue creado con exito");
        }catch(DocumentException | HeadlessException | FileNotFoundException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnreportedocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreporteAdministrativo;
    private javax.swing.JButton btnreporteEstudiante;
    private javax.swing.JButton btnreporteVisitante;
    private javax.swing.JButton btnreportedocente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JLabel lblNOMBRE;
    // End of variables declaration//GEN-END:variables
}
